server:
  port: 8080
  shutdown: graceful
  tomcat:
    accept-count: 100
    threads:
      max: 200
      min-spare: 54
  
spring:
  datasource:
    hikari:
      connection-timeout: 3000
    driver-class-name: org.mariadb.jdbc.Driver
    url: ${datasource.url}
    username: ${datasource.username}
    password: ${datasource.password}
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        jdbc:
        batch_size: 1000
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${oauth2.google.id}
            client-secret: ${oauth2.google.secret}
            scope: email, profile
  mail:
    host: ${mail.host}
    port: ${mail.port}
    username: ${mail.username}
    password: ${mail.password}
    properties:
      mail:
        smtp:
          starttls:
            enable: true
          auth: true
          ssl:
            protocols: TLSv1.2
            

riot_api_key: ${riot_api_key}
  