server:
  port: 8080
  shutdown: graceful
  tomcat: # 해당 서버는 프라이빗 네트워크 상에 리버스 프록시 서버(Nginx)와 다른 WAS들과만 통신해야함
    uri-encoding: UTF-8
    accept-count: 100
    connection-timeout: 30000 # 30sec
    threads:
      max: 200
      min-spare: 54


spring:
  session:
    store-type: redis
  datasource:
    hikari:
      maximum-pool-size: 25
      connection-timeout: 3000
    driver-class-name: org.mariadb.jdbc.Driver
    url: ${datasource.url}
    username: ${datasource.username}
    password: ${datasource.password}
  jpa:
    defer-datasource-initialization: true
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        jdbc:
        batch_size: 1000
  cache:
    type: redis
    redis:
      cache-null-values: true
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${oauth2.google.id}
            client-secret: ${oauth2.google.secret}
            scope: email, profile

lolsearcher:
  master-id: ${lolsearcher.master-id}
  webclient:
    notification-server-url: http://localhost:8082
    reactive-server-url: http://localhost:8081
  redis:
    ttl:
      search-ban: 1440   # 1day
      login-ban: 300     # 5min
      championId: 0      # eternal
      queueId: 0         # eternal
      item: 0            # eternal
      perk: 0            # eternal
      gameVersion: 0     # eternal
  notification:
    token: ${lolsearcher.notification.token}



id-generation:
  nodeId: 1
  class-path: com.lolsearcher