server:
  port: 8080
  shutdown: graceful
  tomcat:
    accept-count: 100
    threads:
      max: 200
      min-spare: 54
  
spring:
  datasource:
    hikari:
      maximum-pool-size: 25
      connection-timeout: 3000
    driver-class-name: org.mariadb.jdbc.Driver
    url: ${datasource.url}
    username: ${datasource.username}
    password: ${datasource.password}
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        jdbc:
        batch_size: 1000
  cache:
    type: redis
    redis:
      cache-null-values: true
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${oauth2.google.id}
            client-secret: ${oauth2.google.secret}
            scope: email, profile
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${mail.username}
    password: ${mail.password}
    properties:
      mail:
        smtp:
          starttls:
            enable: true
          auth: true
          ssl:
            protocols: TLSv1.2
            

riot_api_key: ${riot_api_key}

lolsearcher:
  webclient:
    kr-base-url: https://kr.api.riotgames.com
    asia-base-url: https://asia.api.riotgames.com
  redis:
    ttl:
      ingame: 120 # 2min
      match: 1440 # 1day
      search-ban: 1440 # 1day
      search-abusing: 3600 # 1hour
      login-ban: 300 # 5min
      login-abusing: 300 # 5min
      champions: 0 #eternal
      join-certification: 300 #5min
  kafka:
    topics:
      remaining_match_id:
        name: remaining_match_id
        replica: 1
        partitions: 1
      fail_match_id:
        name: filtered_fail_match_id
        replica: 1
        partitions: 1
      success_match:
        name: success_match
        replica: 1
        partitions: 1
    producers:
      success_match:
        bootstrap_server: localhost:9092
        ack: all
      fail_match_id:
        bootstrap_server: localhost:9092
        ack: all
      remaining_match_id:
        bootstrap_server: localhost:9092
        ack: all